# Generated by Django 2.1.3 on 2019-11-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='driver_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rider_rating',
            field=models.IntegerField(null=True),
        ),
    ]
