# Generated by Django 2.2.5 on 2019-10-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfriends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfriends',
            old_name='friends',
            new_name='users',
        ),
    ]
