# Generated by Django 2.1.3 on 2019-11-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191113_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='driver_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rider_rating',
            field=models.FloatField(null=True),
        ),
    ]
