# Generated by Django 2.2.5 on 2019-11-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191113_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='home_town',
        ),
    ]
