# Generated by Django 2.2.5 on 2019-10-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191014_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.CharField(default='Write a bio to let people know about you!', max_length=120),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Your Name', max_length=50),
        ),
    ]
