# Generated by Django 2.2.5 on 2019-10-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191020_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='/media/default_profile_pic.jpg', upload_to='profile_pic'),
        ),
    ]
