# Generated by Django 2.2.5 on 2019-10-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191020_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='home_town',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(default='Write a bio to let people know about you!', max_length=120),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
