# Generated by Django 2.2.5 on 2019-10-22 03:22

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191022_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='/default/default_profile_pic.jpg', upload_to=users.models.user_directory_path),
        ),
    ]
