branches:
  only:
  - master
  - develop
notifications:
  slack: cs3240-rideon:rA5c3K4w0eZ5GjVwWsY5eazZ
language: python
python:
- '3.6'
install:
- pip install -r requirements-build.txt
script:
- python manage.py test
deploy:
  api_key:
    secure: VIEB9Vm09YKYeyXW6EiGqnP51re0yMHYEofCo33ds/U01e0y6cQ6vhPIEWlnGaKct5EsQPGoF4DxRcErHq85R/ib6AKZzvUq6NJ+Zvj4RB5U1qmTjlwMaDndlFCiUAO4Vw5SDIS3F+5oaLj9iUWgW/d+tVOJoufjdnvkzm4N8wmhTwQ7SAmeJHKhHtRpJCtOlVglAGGXK5wiSfl2tGqskKo9Af6zeSsSijKJHQCNs7KG4vTUUJ3cnBbfBsNyTSLJOZDLJSIX9qJYfetv/5IARHHOWEoY/Xhdc/igrZvskA8uAX77FH7/ht/KDyCrXrsm+UG7gz3sYJXkZzMgUr1CbBSRb1W61URzCYEopqv6wW7yHFva6t7k4LY1XUA4XF57z8z3x+7T6Dlpzjuro+9pnQIeEctyzviQeMsJS3JtV+fzBi0RxZQkry3ajjjrRYaGMRUXEAZXjAT6PlzNngz4IefdB036tpSNhO8YujgzwvBB7E5fTItm2UGYaGntPjv2gg2yxfWqRTdaVqX1xFP+N2/w/piIh2KOo+JAjwdg4YuxbaeKrJ3e+fDTFvdq3pkXW/5LlkLND8crx9/81bscJ/ceR9ajKyjqYyXb1WIlDBYIGUTeXhmwQi/iu17AUMvzcRhHznhvz3NvcqrHByq9jZjJOxiKQX9ozZX8Rm3O18U=
