branches:
  only:
  - master
  - develop
notifications:
  slack: cs3240-rideon:rA5c3K4w0eZ5GjVwWsY5eazZ
language: python
python:
- '3.6'
install:
- pip install -r requirements-build.txt
script:
- python manage.py migrate
- python manage.py test
deploy:
  provider: heroku
  app: uva-ride-on
  api_key:
    secure: lEAjWroXvwgda9V9pOEGch0x+Svq0N3S4ePSmPThxl9pbSnE+qbvAhGhxUPVfonmqNWrd3cjP9ykLGZYH3ikuSKsN78dkVngDFY0xPfyokp7BHr/YUdlMa/X87hdpNiDNAnuIa8jZaVM9SRrw8ZxsejFcumfZqYebK5LfDrSYte7Mbr1ete0+YL/gGbitkon3cv+4P985/TfmXprplFjL7CR1FPzgjM0t0eon/D9ZpQcME7ZKKmK8fbYyZncGsZtIoZ+HCHp1UoIP1Fc+n/y//bk03yjfe61dZYR3oQXz8y3v1orPuncP9luMu4HSCWdq9JpQoQVoD+uTMPQ/3PGPWAaumGfzSRuWgZE+tmP/fHC3ZEYxuXD8w73AvzKgm9ga6zkRpWS4JIeZ/RZmBbp3vYWO8co/rE7Gtc5ejNU4zMcDLfWgWY7LV0EtCEdBZE5mgXjoBWIHKB5zY2KK5TEixrqRlLaNTqnhrjA+/NniDDFw50jvXYr2WiWAqpyB5b4V0HGi7w53ace1gRObybrV2qUEH8HG9EmIgiGKcshXPYSPRfxWWGdCOXuQZEsxw0SD1kL3023cTHAY/5XCPkn4TzY4WgTd5r6x78GSo8/nkPQBTKc5fljnGtipF5KVw436xecam/1KBnmq2yV/jHV5+5EpeSdTt8GYw3BBZmEx2E=
