# Generated by Django 2.2.5 on 2019-10-20 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderreview',
            name='by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riderreview',
            name='drive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drives.Drive'),
        ),
        migrations.AddField(
            model_name='riderreview',
            name='of',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='dropoff_in_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drives.Drive'),
        ),
        migrations.AddField(
            model_name='driverreview',
            name='by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverreview',
            name='drive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drives.Drive'),
        ),
        migrations.AddField(
            model_name='driverreview',
            name='of',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drive',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drive',
            name='end_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_location', to='drives.Location'),
        ),
        migrations.AddField(
            model_name='drive',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='passengers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drive',
            name='start_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_location', to='drives.Location'),
        ),
    ]
