# Generated by Django 2.2.5 on 2019-10-10 23:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='by', to=settings.AUTH_USER_MODEL)),
                ('drive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drives.Drive')),
                ('of', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
