# Generated by Django 2.2.5 on 2019-10-13 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 19, 6, 2, 475597, tzinfo=utc)),
        ),
    ]
