# Generated by Django 2.2.5 on 2019-10-11 01:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drives', '0002_driverreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverreview',
            name='by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driverreview',
            name='of',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RiderReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_by', to=settings.AUTH_USER_MODEL)),
                ('drive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drives.Drive')),
                ('of', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
