# Generated by Django 2.2.5 on 2019-10-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0002_auto_20191019_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='end_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drive',
            name='end_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drive',
            name='end_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drive',
            name='end_street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drive',
            name='end_zip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drive',
            name='start_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drive',
            name='start_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drive',
            name='start_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drive',
            name='start_street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drive',
            name='start_zip',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='end_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='start_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
