# Generated by Django 2.1.3 on 2019-11-02 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drives', '0002_auto_20191028_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('waypoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waypoint', to='drives.Location')),
            ],
        ),
        migrations.AlterField(
            model_name='drive',
            name='requestList',
            field=models.ManyToManyField(blank=True, related_name='requestList', to='drives.RideApplication'),
        ),
    ]
