# Generated by Django 2.1.3 on 2019-11-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0002_auto_20191104_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='dropoff_in_drive',
        ),
        migrations.AddField(
            model_name='drive',
            name='waypointList',
            field=models.ManyToManyField(blank=True, related_name='waypointList', to='drives.Location'),
        ),
    ]
