# Generated by Django 2.1.3 on 2019-10-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0003_auto_20191014_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='end_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_location', to='drives.Location'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='start_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_location', to='drives.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinates_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinates_y',
            field=models.FloatField(),
        ),
    ]
