# Generated by Django 2.1.3 on 2019-11-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0003_auto_20191104_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideapplication',
            name='waypoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waypoint', to='drives.Location'),
        ),
    ]
