# Generated by Django 2.2.5 on 2019-10-20 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0003_auto_20191019_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drive',
            old_name='end_city',
            new_name='end_administrative_area_level_1',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='end_id',
            new_name='end_country',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='end_location',
            new_name='end_locality',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='end_state',
            new_name='end_postal_code',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='end_street',
            new_name='end_route',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='end_zip',
            new_name='end_street_number',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='start_city',
            new_name='start_administrative_area_level_1',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='start_id',
            new_name='start_country',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='start_location',
            new_name='start_locality',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='start_state',
            new_name='start_postal_code',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='start_street',
            new_name='start_route',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='start_zip',
            new_name='start_street_number',
        ),
    ]
