# Generated by Django 2.1.3 on 2019-10-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0004_auto_20191015_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coordinates_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinates_y',
            field=models.FloatField(default=0),
        ),
    ]
