# Generated by Django 2.1.3 on 2019-10-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0003_auto_20191011_0138'),
        ('drives', '0004_auto_20191014_1735'),
    ]

    operations = [
    ]
