# Generated by Django 2.2.5 on 2019-10-17 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0006_driverreview_riderreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riderreview',
            name='by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riderreview',
            name='drive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drives.Drive'),
        ),
        migrations.AddField(
            model_name='riderreview',
            name='of',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverreview',
            name='by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverreview',
            name='drive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drives.Drive'),
        ),
        migrations.AddField(
            model_name='driverreview',
            name='of',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
