# Generated by Django 2.1.3 on 2019-10-18 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drives', '0007_auto_20191017_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='requestList',
            field=models.ManyToManyField(blank=True, related_name='requestList', to=settings.AUTH_USER_MODEL),
        ),
    ]
